const CLUBES = [
    /*CONMEBOL - América do Sul*/

    /* Clubes da Argentina */
    { nome: "Boca Juniors", id: "boca-juniors", pais: "ARG", pagina: "america-sul.html" },
    { nome: "River Plate", id: "river-plate-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Independiente", id: "independiente", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Racing Club", id: "racing-club", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Lorenzo", id: "san-lorenzo-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Estudiantes de La Plata", id: "estudiantes-de-la-plata", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Newell's Old Boys", id: "newells-old-boys", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Rosario Central", id: "rosario-central", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Velez Sarsfield", id: "velez-sarsfield", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentinos Juniors", id: "argentinos-juniors", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Club Atlético Huracán", id: "huracan", pais: "ARG", pagina: "america-sul.html" },
    { nome: "gimnasia y Esgrima La Plata", id: "gimnasia-y-esgrima-la-plata", pais: "ARG", pagina: "america-sul.html" },
    { nome: "gimnasia y Esgrima de Mendoza", id: "gimnasia-y-esgrima-de-mendoza", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Lanús", id: "lanus", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Banfield", id: "banfield", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Talleres de Córdoba", id: "talleres-de-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Colón de Santa Fe", id: "colon-de-santa-fe", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Unión de Santa Fe", id: "union-de-santa-fe", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensa y Justicia", id: "defensa-y-justicia", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Godoy Cruz", id: "godoy-cruz", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Arsenal de Sarandi", id: "arsenal-de-sarandi", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Tucumán", id: "atletico-tucuman", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Tigre", id: "tigre", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Platense", id: "platense-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Barracas Central", id: "barracas-central", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Central Córdoba", id: "central-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Instituto de Córdoba", id: "instituto-de-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Sarmiento", id: "sarmiento", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Belgrano de Córdoba", id: "belgrano-de-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Patronato", id: "patronato", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Aldosivi", id: "aldosivi", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Independiente Rivadavia", id: "independiente-rivadavia", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Boca Unidos", id: "boca-unidos", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Quilmes", id: "quilmes", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Almagro", id: "almagro", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Martín de San Juan", id: "san-martin-de-san-juan", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Martín de Tucumán", id: "san-martin-de-tucuman", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Gimnasia de Jujuy", id: "gimnasia-de-jujuy", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Ferro Carril Oeste", id: "ferro-carril-oeste", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Olimpo", id: "olimpo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Tristán Suárez", id: "tristan-suarez", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Chacarita Juniors", id: "chacarita-juniors", pais: "ARG", pagina: "america-sul.html" },
    { nome: "All Boys", id: "all-boys", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético de Rafaela", id: "atletico-de-rafaela", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Los Andes", id: "los-andes", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Riestra", id: "deportivo-riestra", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Agropecuario", id: "agropecuario", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Brown de Adrogué", id: "brown-de-adrogué", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensores de Belgrano", id: "defensores-de-belgrano", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Morón", id: "deportivo-moron", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Almirante Brown", id: "almirante-brown", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Mitre", id: "atletico-mitre", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Nueva Chicago", id: "nueva-chicago", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Santamarina", id: "santamarina", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Club Atlético Temperley", id: "club-atletico-temperley", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Villa Dálmine", id: "villa-dalmine", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Acassuso", id: "acassuso", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentino de Quilmes", id: "argentino-de-quilmes", pais: "ARG", pagina: "america-sul.html" },
    { nome: "El Porvenir", id: "el-porvenir", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensores de Cambaceres", id: "defensores-de-cambaceres", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlanta", id: "atlanta-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Colegiales", id: "atletico-colegiales-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Comunicaciones", id: "comunicaciones", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Club Deportivo Español", id: "club-deportivo-espanol", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensores Unidos", id: "defensores-unidos", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Estudiantes de Buenos Aires", id: "estudiantes-ba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Fénix", id: "fenix-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Flandria", id: "flandria", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Sacachispas", id: "sacachispas", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Miguel", id: "san-miguel", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Telmo", id: "san-telmo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Talleres (RE)", id: "talleres-re", pais: "ARG", pagina: "america-sul.html" },
    { nome: "UAI Urquiza", id: "uai-urquiza", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentino (Merlo)", id: "argentino-de-merlo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Armenio", id: "deportivo-armenio", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Berazategui", id: "berazategui", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Cañuelas", id: "canuelas", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Laferrere", id: "deportivo-laferrere", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Dock Sud", id: "dock-sud", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Sportivo Barracas", id: "sportivo-barracas", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Sportivo Italiano", id: "sportivo-italiano", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Ferrocarril Midland", id: "ferrocarril-midland", pais: "ARG", pagina: "america-sul.html" },
    { nome: "J.J. Urquiza", id: "jj-urquiza", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Merlo", id: "deportivo-merlo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Luján", id: "lujan", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Martín (Burzaco)", id: "san-martin-burzaco", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentino (Rosário)", id: "argentino-de-rosario", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlas-ARG", id: "atlas-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Central Ballester", id: "central-ballester", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Centro Español", id: "centro-espanol", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Claypole", id: "claypole", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Paraguayo", id: "deportivo-paraguayo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Juventud Unida", id: "juventud-unida", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Liniers", id: "liniers", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Lugano", id: "atletico-lugano", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Muñiz", id: "deportivo-muniz", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Puerto Nuevo", id: "puerto-nuevo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Real Pilar", id: "real-pilar", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Yupanqui", id: "yupanqui", pais: "ARG", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "ARG", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "ARG", pagina: "america-sul.html" },


    /* Clubes da Bolívia */
    { nome: "The Strongest", id: "the-strongest", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Bolívar", id: "bolivar", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Jorge Wilstermann", id: "jorge-wilstermann", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Blooming", id: "blooming", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Oriente Petrolero", id: "oriente-petrolero", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Aurora", id: "aurora", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Nacional Potosí", id: "nacional-potosi", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Real Santa Cruz", id: "real-santa-cruz", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Guabirá", id: "guabira", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Royal Pari", id: "royal-pari", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Universitario de Vinto", id: "universitario-de-vinto", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Independiente Petrolero", id: "independiente-petrolero", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Always Ready", id: "always-ready", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Real Potosí", id: "real-potosi", pais: "BOL", pagina: "america-sul.html" },
    { nome: "San José", id: "san-jose", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Universitario de Sucre", id: "universitario-de-sucre", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Palmaflor", id: "palmaflor", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Vaca Díez", id: "vaca-diez", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Chaco Petrolero", id: "chaco-petrolero", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Destroyer's", id: "destroyers", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Unión Central", id: "union-central", pais: "BOL", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BOL", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BOL", pagina: "america-sul.html" },


    /* Clubes do Brasil */
    { nome: "Santos FC", id: "santos-fc", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Corinthians", id: "corinthians", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Chapecoense", id: "chapecoense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Botafogo-RJ", id: "botafogo-rj", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Náutico-RR", id: "nautico-rr", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Náutico-PE", id: "nautico-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Santa Cruz-PE", id: "santa-cruz-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Sport-PE", id: "sport", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Globo-RN", id: "globo-rn", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Fortaleza", id: "fortaleza", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Ceará", id: "ceara", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Floresta", id: "floresta", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Cuiabá", id: "cuiaba", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Bahia", id: "bahia", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Internacional", id: "internacional", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Grêmio", id: "gremio", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Brusque", id: "brusque", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Luverdense", id: "luverdense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Serra Talhada", id: "serra-talhada", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Manaus", id: "manaus", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Treze - PB", id: "treze-pb", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Botafogo- PB", id: "botafogo-pb", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Flamengo", id: "flamengo", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Palmeiras", id: "palmeiras", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Central", id: "central", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Porto-PE", id: "porto-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Criciúma", id: "criciuma", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Belo Jardim", id: "belo-jardim", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Chã Grande", id: "cha-grande", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Paulo", id: "sao-paulo", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Fluminense", id: "fluminense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Vasco da Gama", id: "vasco-da-gama", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Mirassol", id: "mirassol", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Cruzeiro", id: "cruzeiro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Athletico Paranaense", id: "athletico-paranaense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Mineiro", id: "atletico-mineiro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Petrolina", id: "petrolina", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Paysandu", id: "paysandu", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Avaí", id: "avai", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Athletic Club", id: "athletic-club", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Goianiense", id: "atletico-goianiense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Goiás", id: "goias", pais: "BRA", pagina: "america-sul.html" },
    { nome: "CRB", id: "crb", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Coritiba", id: "coritiba", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Paraná Clube", id: "parana-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Londrina", id: "londrina", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Afogados da Ingazeira", id: "afogados-da-ingazeira", pais: "BRA", pagina: "america-sul.html" },
    { nome: "ASA de Arapiraca", id: "asa-de-arapiraca", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Ramalat Sport Club", id: "ramalat-sport-club", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Rio Branco-AC", id: "rio-branco-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Acreano", id: "atletico-acreano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Galvez Esporte Clube", id: "galvez-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Humaitá Futebol Clube", id: "humaita-futebol-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Francisco Futebol Clube", id: "sao-francisco-futebol-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "ADESG", id: "adesg", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Náuas Esporte Clube", id: "nauas-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Raimundo-RR", id: "sao-raimundo-rr", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Tombense", id: "tombense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "XV de Piracicaba", id: "xv-de-piracicaba", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Ponte Preta", id: "ponte-preta", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Guarani", id: "guarani-bra", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Salgueiro", id: "salgueiro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Fast Clube", id: "fast-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Raimundo-AM", id: "sao-raimundo-am", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Princesa do Solimões Esporte Clube", id: "princesa-do-solimoes-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Penarol-AM", id: "penarol-am", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Operário Esporte Clube", id: "operario-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Iranduba Futebol Clube", id: "iranduba-futebol-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Rio Negro", id: "rio-negro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Amazonas", id: "amazonas", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Boa Esporte", id: "boa-esporte", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Íbis", id: "ibis", pais: "BRA", pagina: "america-sul.html" },
    { nome: "E.C.Vitória", id: "e-c-vitoria", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Juventude", id: "juventude", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Caxias do Sul", id: "caxias-do-sul", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Figueirense", id: "figueirense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "América Pernambucano", id: "america-pernambucano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "América de Natal", id: "america-de-natal", pais: "BRA", pagina: "america-sul.html" },
    { nome: "ABC", id: "abc", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Confiança", id: "confianca", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Lagarto", id: "lagarto", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Paragominas", id: "paragominas", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Cianorte", id: "cianorte", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Icasa", id: "icasa", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Clube Juventus-AC", id: "atletico-clube-juventus-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Clube Atlético Juventus-SP", id: "clube-atletico-juventus-sp", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Nacional-AM", id: "nacional-am", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Nacional-SP", id: "nacional-sp", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Independência-AC", id: "independencia-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Acriano", id: "acriano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Alto Acre", id: "alto-acre", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Andirá Esporte Clube", id: "andira-ec", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Grêmio Acreano", id: "gremio-acreano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Plácido de Castro", id: "placido-de-castro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Vasco da Gama-AC", id: "vasco-da-gama-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Santa Cruz-AC", id: "santa-cruz-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Amax", id: "amax", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Jaguar-PE", id: "jaguar-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Retrô", id: "retro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Pernambucano", id: "atletico-pernambucano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Vera Cruz-PE", id: "vera-cruz-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Vitória-PE", id: "vitoria-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Campinense", id: "campinense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Altos-PI", id: "altos-pi", pais: "BRA", pagina: "america-sul.html" },
    { nome: "River-PI", id: "river-pi", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Flamengo-PI", id: "flamengo-pi", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Parnahyba-PI", id: "parnahyba-pi", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Moto Club-MA", id: "moto-club-ma", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Sampaio Corrêa-MA", id: "sampaio-correa-ma", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Maranhão (MAC)", id: "maranhao-mac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Imperatriz", id: "imperatriz", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Tocantins", id: "tocantins", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Patriotas-PR", id: "patriotas-pr", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Decisão", id: "decisao", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Brasiliense", id: "brasiliense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Gama", id: "gama", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Portuguesa-RJ", id: "portuguesa-rj", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Portuguesa-SP", id: "portuguesa-sp", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Maguary", id: "maguary", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Volta Redonda", id: "volta-redonda", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },

    /* Clubes do Chile */
    { nome: "Colo-Colo", id: "colo-colo", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Universidad de Chile", id: "universidad-de-chile", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Universidad Católica del Chile", id: "universidad-catolica-del-chile", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Deportivo Union Espaola", id: "union-espanola", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Audax Italiano", id: "audax-italiano", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Everton de Viña del Mar", id: "everton-de-vina-del-mar", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Santiago Wanderers", id: "santiago-wanderers", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Nublense", id: "nublense", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Huachipato", id: "huachipato", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Palestino", id: "palestino", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Cobresal", id: "cobresal", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Cobreloa", id: "cobreloa", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Temuco", id: "deportes-temuco", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Rangers de Talca", id: "rangers-chi", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Recoleta", id: "deportes-recoleta-chi", pais: "CHI", pagina: "america-sul.html" },

    { nome: "Deportes Concepción", id: "deportes-concepcion", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Curicó Unido", id: "curico-unido", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Santiago Morning", id: "santiago-morning", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Universidad de Concepción", id: "universidad-de-concepcion", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Iquique", id: "deportes-iquique", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Antofagasta", id: "deportes-antofagasta", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Unión La Calera", id: "union-la-calera", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Limache", id: "deportes-limache", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Unión San Felipe", id: "union-san-felipe", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Magallanes", id: "deportes-magallanes", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Copiapó", id: "deportes-copiapo", pais: "CHI", pagina: "america-sul.html" },
    { nome: "San Luis de Quillota", id: "san-luis-de-quillota", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Puerto Montt", id: "deportes-puerto-montt", pais: "CHI", pagina: "america-sul.html" },
    { nome: "San Marcos de Arica", id: "san-marcos-de-arica", pais: "CHI", pagina: "america-sul.html" },
    { nome: "San Antonio Unido", id: "san-antonio-unido", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Lota Schwager", id: "lota-schwager", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Santa Cruz", id: "deportes-santa-cruz", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Melipilla", id: "deportes-melipilla", pais: "CHI", pagina: "america-sul.html" },
    { nome: "AC Barnechea", id: "ac-barnechea", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Linares", id: "deportes-linares", pais: "CHI", pagina: "america-sul.html" },
    { nome: "CDSC Iberia", id: "cdsc-iberia", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Fernández Vial", id: "fernandez-vial", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Trasandino", id: "trasandino", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Concón National", id: "concon-national", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Valdivia", id: "deportes-valdivia", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Naval", id: "deportes-naval", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Lautaro de Buin", id: "lautaro-de-buin", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Provincial Ovalle", id: "provincial-ovalle", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Colchagua", id: "deportes-colchagua", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Santiago City", id: "santiago-city", pais: "CHI", pagina: "america-sul.html" },
    { nome: "CD Rengo", id: "cd-rengo", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Colina", id: "deportes-colina", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Provincial Osorno", id: "deportes-provincial-osorno", pais: "CHI", pagina: "america-sul.html" },
    { nome: "General Velásquez", id: "general-velasquez", pais: "CHI", pagina: "america-sul.html" },
    { nome: "CD Malleco Unido", id: "cd-malleco-unido", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Independiente Cauquenes", id: "independiente-cauquenes", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Vallenar", id: "deportes-vallenar", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Deportivo Real Juventud San Joaquín", id: "real-juventud-san-joaquin", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Municipal Mejillones", id: "municipal-mejillones", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Rodelindo Román", id: "rodelindo-roman", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Ovalle", id: "deportes-ovalle", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes La Pintana", id: "deportes-la-pintana", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Corporación Deportiva Comunal Cabrera", id: "corporacion-deportiva-comunal-cabrera", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Maipo Quilicura", id: "deportes-maipo-quilicura", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Atlético Oriente", id: "atletico-oriente", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Unión Compañías", id: "union-companias", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Corporación Municipal de Deporte Puente Alto", id: "corporacion-municipal-deporte-puente-alto", pais: "CHI", pagina: "america-sul.html" },
    { nome: "CDSC Aguará", id: "cdsc-aguara", pais: "CHI", pagina: "america-sul.html" },
    { nome: "CD Quillón", id: "cd-quillon", pais: "CHI", pagina: "america-sul.html" },
    { nome: "CSD Buenos Aires", id: "csd-buenos-aires", pais: "CHI", pagina: "america-sul.html" },
    { nome: "CSD Cajón del Maipo", id: "csd-cajon-del-maipo", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Chimbarongo Fútbol Club", id: "chimbarongo-futbol-club", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deporte Puente Alto", id: "deporte-puente-alto", pais: "CHI", pagina: "america-sul.html" },
    { nome: "CD Tricolor Municipal de Paine", id: "cd-tricolor-municipal-de-paine", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Deportivo y Social Constitución Unida", id: "club-deportivo-social-constitucion-unida", pais: "CHI", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "CHI", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "CHI", pagina: "america-sul.html" },

    /* Clubes da Colômbia*/
    { nome: "Atlético Nacional", id: "atletico-nacional", pais: "COL", pagina: "america-sul.html" },
    { nome: "Millonarios FC", id: "millonarios", pais: "COL", pagina: "america-sul.html" },
    { nome: "Águilas Doradas", id: "aguilas-doradas", pais: "COL", pagina: "america-sul.html" },
    { nome: "Alianza", id: "alianza", pais: "COL", pagina: "america-sul.html" },
    { nome: "Atlético Bucaramanga", id: "atletico-bucaramanga", pais: "COL", pagina: "america-sul.html" },
    { nome: "América de Cali", id: "america-de-cali", pais: "COL", pagina: "america-sul.html" },
    { nome: "Boyacá Chicó", id: "boyaca-chico", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportes Tolima", id: "deportes-tolima", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportivo Cali", id: "deportivo-cali", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportivo Pasto", id: "deportivo-pasto", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportivo Pereira", id: "deportivo-pereira", pais: "COL", pagina: "america-sul.html" },
    { nome: "Envigado", id: "envigado", pais: "COL", pagina: "america-sul.html" },
    { nome: "Fortaleza CEIF", id: "fortaleza-ceif", pais: "COL", pagina: "america-sul.html" },
    { nome: "Independiente Medellín", id: "independiente-medellin", pais: "COL", pagina: "america-sul.html" },
    { nome: "Jaguares de Córdoba", id: "jaguares de cordoba", pais: "COL", pagina: "america-sul.html" },
    { nome: "Junior de Barranquilla", id: "junior-barranquilla", pais: "COL", pagina: "america-sul.html" },
    { nome: "La Equidad", id: "la-equidad", pais: "COL", pagina: "america-sul.html" },
    { nome: "Once Caldas", id: "once-caldas", pais: "COL", pagina: "america-sul.html" },
    { nome: "Patriotas", id: "patriotas-col", pais: "COL", pagina: "america-sul.html" },
    { nome: "Santa Fe", id: "santa-fe", pais: "COL", pagina: "america-sul.html" },
    { nome: "Atlético FC", id: "atletico-fc", pais: "COL", pagina: "america-sul.html" },
    { nome: "Atlético Huila", id: "atletico-huila", pais: "COL", pagina: "america-sul.html" },
    { nome: "Barranquilla FC", id: "barranquilla-fc", pais: "COL", pagina: "america-sul.html" },
    { nome: "Boca Juniors de Cali", id: "boca-juniors-cali", pais: "COL", pagina: "america-sul.html" },
    { nome: "Bogotá FC", id: "bogota-fc", pais: "COL", pagina: "america-sul.html" },
    { nome: "Cúcuta Deportivo", id: "cucuta-deportivo", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportes Quindío", id: "deportes-quindio", pais: "COL", pagina: "america-sul.html" },
    { nome: "Internacional Palmira", id: "internacional-palmira", pais: "COL", pagina: "america-sul.html" },
    { nome: "Itagüí Leones", id: "itagui-leones", pais: "COL", pagina: "america-sul.html" },
    { nome: "Llaneros", id: "llaneros", pais: "COL", pagina: "america-sul.html" },
    { nome: "Orsomarso", id: "orsomarso", pais: "COL", pagina: "america-sul.html" },
    { nome: "Real Cartagena", id: "real-cartagena", pais: "COL", pagina: "america-sul.html" },
    { nome: "Real Cundinamarca", id: "real-cundinamarca", pais: "COL", pagina: "america-sul.html" },
    { nome: "Real Santander", id: "real-santander", pais: "COL", pagina: "america-sul.html" },
    { nome: "Tigres", id: "tigres-col", pais: "COL", pagina: "america-sul.html" },
    { nome: "Unión Magdalena", id: "union-magdalena", pais: "COL", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "COL", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "COL", pagina: "america-sul.html" },

    /* Clubes do Equador */
    { nome: "LDU Quito", id: "ldu-quito", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Barcelona de Guayaquil", id: "barcelona-de-guayaquil", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Independiente del Valle", id: "independiente-del-valle", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Independiente Juniors", id: "independiente-juniors", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Emelec", id: "emelec", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Aucas", id: "aucas", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Guayaquil City", id: "guayaquil-city", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Manta FC", id: "manta-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Olmedo", id: "olmedo", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Deportivo Quito", id: "deportivo-quito", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Universidad Católica del Ecuador", id: "universidad-catolica-ecuador", pais: "ECU", pagina: "america-sul.html" },
    { nome: "LDU Portoviejo", id: "ldu-portoviejo", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Macará", id: "macara", pais: "ECU", pagina: "america-sul.html" },
    { nome: "El Nacional", id: "el-nacional", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Mushuc Runa", id: "mushuc-runa", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Técnico Universitario", id: "tecnico-universitario", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Orense SC", id: "orense-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Imbabura SC", id: "imbabura-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Deportivo Cuenca", id: "deportivo-cuenca", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Delfín SC", id: "delfin-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Deportivo Quevedo", id: "deportivo-quevedo", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Deportivo Azogues", id: "deportivo-azogues", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Gualaceo SC", id: "gualaceo-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Cumbaya FC", id: "cumbaya-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Vinotinto FC", id: "vinotinto-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Atlético Vinotinto", id: "atletico-vinotinto", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Libertad FC", id: "libertad-fc-ecu", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Chacaritas FC", id: "chacaritas-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Nueve de Octubre", id: "nueve-de-octubre", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Leones FC", id: "leones-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Buhos ULVR", id: "buhos-ulvr", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Clan Juvenil", id: "clan-juvenil", pais: "ECU", pagina: "america-sul.html" },
    { nome: "C.D. Espoli", id: "cd-espoli", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Fuerza Amarilla SC", id: "fuerza-amarilla-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "CSCD Grecia", id: "cscd-grecia", pais: "ECU", pagina: "america-sul.html" },
    { nome: "UT Cotopaxi", id: "ut-cotopaxi", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Atlético Porteño", id: "atletico-porteno", pais: "ECU", pagina: "america-sul.html" },
    { nome: "C.S. Patria", id: "cs-patria-ecu", pais: "ECU", pagina: "america-sul.html" },
    { nome: "C.D. Santa Rita", id: "cd-santa-rita", pais: "ECU", pagina: "america-sul.html" },
    { nome: "América de Quito", id: "america-de-quito", pais: "ECU", pagina: "america-sul.html" },
    { nome: "San Antonio", id: "san-antonio", pais: "ECU", pagina: "america-sul.html" },
    { nome: "CD Municipal Cañar", id: "cd-municipal-canar", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Colón de Portoviejo", id: "colon-de-portoviejo", pais: "ECU", pagina: "america-sul.html" },
    { nome: "CD Ferroviarios", id: "cd-ferroviarios", pais: "ECU", pagina: "america-sul.html" },
    { nome: "CSD Vargas Torres", id: "csd-vargas-torres", pais: "ECU", pagina: "america-sul.html" },
    { nome: "22 de Julio FC", id: "clube-22-de-julio-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "ECU", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "ECU", pagina: "america-sul.html" },

    /* Clubes do Paraguai */
    { nome: "Cerro Porteño", id: "cerro-porteno", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Nacional", id: "nacional-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Guaraní", id: "guarani-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Rubio Ñu", id: "rubio-nu", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Atlético Colegiales", id: "atletico-colegiales-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Tacuary", id: "tacuary", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sportivo Luqueño", id: "sportivo-luqueno", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sol de América", id: "sol-de-america", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Díaz", id: "general-diaz", pais: "PAR", pagina: "america-sul.html" },
    { nome: "River Plate", id: "river-plate-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "29 de Septiembre", id: "clube-29-de-septiembre", pais: "PAR", pagina: "america-sul.html" },
    { nome: "3 de Febrero", id: "clube-3-de-febrero", pais: "PAR", pagina: "america-sul.html" },
    { nome: "1º de Marzo", id: "clube-1-de-marzo", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Martín Ledesma", id: "general-martin-ledesma", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Cristóbal Colón", id: "cristobal-colon", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Capitán Figari", id: "capitan-figari", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Atlético Tembetary", id: "atletico-tembetary", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Atlântida", id: "atlantida", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Atlético Juventud", id: "atletico-juventud", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Caballero San Felipe", id: "general-caballero-san-felipe", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Oriental", id: "oriental-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Valois Rivarola", id: "valois-rivarola-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sport Colonial", id: "sport-colonial", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Benjamín Aceval", id: "benjamin-aceval", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Libertad", id: "libertad-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Presidente Hayes", id: "presidente-hayes", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Olímpia", id: "olimpia", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sportivo Trinidense", id: "sportivo-trinidense", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Silvio Pettirossi", id: "silvio-pettirossi", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Fernando de la Mora", id: "fernando-de-la-mora", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Independiente de Campo Grande", id: "independiente-campo-grande", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sport Colombia", id: "sport-colombia", pais: "PAR", pagina: "america-sul.html" },
    { nome: "San Lorenzo", id: "san-lorenzo-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Resistencia", id: "resistencia-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sportivo Iteño", id: "sportivo-iteno", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Caballero", id: "general-caballero", pais: "PAR", pagina: "america-sul.html" },
    { nome: "3 de Noviembre", id: "clube-3-de-noviembre", pais: "PAR", pagina: "america-sul.html" },
    { nome: "12 de Octubre", id: "clube-12-de-octubre", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Olímpia de Itá", id: "olimpia-de-ita", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Caballero de Campo Grande", id: "general-caballero-campo-grande", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Pilcomayo", id: "pilcomayo", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Deportivo Pinozá", id: "deportivo-pinoza", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Deportivo Recoleta", id: "deportivo-recoleta", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sportivo Ameliano", id: "sportivo-ameliano", pais: "PAR", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "PAR", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "PAR", pagina: "america-sul.html" },

    /*Clubes do Peru */
    { nome: "Alianza Lima", id: "alianza-lima", pais: "PER", pagina: "america-sul.html" },
    { nome: "Sporting Cristal", id: "sporting-cristal", pais: "PER", pagina: "america-sul.html" },
    { nome: "Universitario", id: "universitario-per", pais: "PER", pagina: "america-sul.html" },
    { nome: "FBC Melgar", id: "fbc-melgar", pais: "PER", pagina: "america-sul.html" },
    { nome: "Club Cienciano", id: "club-cienciano", pais: "PER", pagina: "america-sul.html" },
    { nome: "Universidad César Vallejo", id: "universidad-cesar-vallejo", pais: "PER", pagina: "america-sul.html" },
    { nome: "Sport Boys", id: "sport-boys", pais: "PER", pagina: "america-sul.html" },
    { nome: "León de Huánuco", id: "leon-de-huanuco", pais: "PER", pagina: "america-sul.html" },
    { nome: "Ayacucho FC", id: "ayacucho-fc", pais: "PER", pagina: "america-sul.html" },
    { nome: "José Gálvez FBC", id: "jose-galvez-fbc", pais: "PER", pagina: "america-sul.html" },
    { nome: "Cusco FC", id: "cusco-fc", pais: "PER", pagina: "america-sul.html" },
    { nome: "Alianza Atlético", id: "alianza-atletico", pais: "PER", pagina: "america-sul.html" },
    { nome: "Juan Aurich", id: "juan-aurich", pais: "PER", pagina: "america-sul.html" },
    { nome: "Universidad Técnica de Cajamarca", id: "universidad-tecnica-de-cajamarca", pais: "PER", pagina: "america-sul.html" },
    { nome: "Unión Comercio", id: "union-comercio", pais: "PER", pagina: "america-sul.html" },
    { nome: "Alianza Universidad", id: "alianza-universidad", pais: "PER", pagina: "america-sul.html" },
    { nome: "Sport Huancayo", id: "sport-huancayo", pais: "PER", pagina: "america-sul.html" },
    { nome: "Los Chankas", id: "los-chankas", pais: "PER", pagina: "america-sul.html" },
    { nome: "Deportivo Coopsol", id: "deportivo-coopsol", pais: "PER", pagina: "america-sul.html" },
    { nome: "Comerciantes Unidos", id: "comerciantes-unidos", pais: "PER", pagina: "america-sul.html" },
    { nome: "Deportivo Municipal", id: "deportivo-municipal", pais: "PER", pagina: "america-sul.html" },
    { nome: "Carlos A. Mannucci", id: "carlos-a-mannucci", pais: "PER", pagina: "america-sul.html" },
    { nome: "Atlético Grau", id: "atletico-grau", pais: "PER", pagina: "america-sul.html" },
    { nome: "Deportivo Garcilaso", id: "deportivo-garcilaso", pais: "PER", pagina: "america-sul.html" },
    { nome: "AD Tarma", id: "ad-tarma", pais: "PER", pagina: "america-sul.html" },
    { nome: "Universidad San Martin Porres", id: "universidad-san-martin-porres", pais: "PER", pagina: "america-sul.html" },
    { nome: "FC Cajamarca", id: "fc-cajamarca", pais: "PER", pagina: "america-sul.html" },
    { nome: "Unión Huaral", id: "union-huaral", pais: "PER", pagina: "america-sul.html" },
    { nome: "Academia Cantolao", id: "academia-cantolao", pais: "PER", pagina: "america-sul.html" },
    { nome: "Juan Pablo II", id: "juan-pablo-ii", pais: "PER", pagina: "america-sul.html" },
    { nome: "Deportivo Binacional", id: "deportivo-binacional", pais: "PER", pagina: "america-sul.html" },
    { nome: "Carlos Stein", id: "carlos-stein", pais: "PER", pagina: "america-sul.html" },
    { nome: "CD Walter Ormeño", id: "cd-walter-ormeno", pais: "PER", pagina: "america-sul.html" },
    { nome: "CD Alfonso Ugarte", id: "cd-alfonso-ugarte", pais: "PER", pagina: "america-sul.html" },
    { nome: "Santos de Nasca", id: "santos-de-nasca-per", pais: "PER", pagina: "america-sul.html" },
    { nome: "Deportivo Llacuabamba", id: "deportivo-llacuabamba", pais: "PER", pagina: "america-sul.html" },
    { nome: "CD Moquegua", id: "cd-moquegua", pais: "PER", pagina: "america-sul.html" },
    { nome: "Pirata FC", id: "pirata-fc", pais: "PER", pagina: "america-sul.html" },
    { nome: "Sport Áncash", id: "sport-ancash", pais: "PER", pagina: "america-sul.html" },
    { nome: "Atlético Minero", id: "atletico-minero", pais: "PER", pagina: "america-sul.html" },
    { nome: "Cobresol FBC", id: "cobresol-fbc", pais: "PER", pagina: "america-sul.html" },
    { nome: "Colegio Nacional de Iquitos", id: "colegio-nacional-de-iquitos", pais: "PER", pagina: "america-sul.html" },
    { nome: "Los Caimanes", id: "los-caimanes", pais: "PER", pagina: "america-sul.html" },
    { nome: "CD Pacífico", id: "cd-pacifico", pais: "PER", pagina: "america-sul.html" },
    { nome: "San Simón", id: "san-simon", pais: "PER", pagina: "america-sul.html" },
    { nome: "Atlético Torino", id: "atletico-torino", pais: "PER", pagina: "america-sul.html" },
    { nome: "CD Willy Serrato", id: "cd-willy-serrato", pais: "PER", pagina: "america-sul.html" },
    { nome: "Sport Victoria", id: "sport-victoria", pais: "PER", pagina: "america-sul.html" },
    { nome: "Coronel Bolognesi", id: "coronel-bolognesi", pais: "PER", pagina: "america-sul.html" },
    { nome: "Bentin Tacna Heroica", id: "bentin-tacna-heroica", pais: "PER", pagina: "america-sul.html" },
    { nome: "Chavelines Juniors", id: "chavelines-juniors", pais: "PER", pagina: "america-sul.html" },
    { nome: "Comerciantes FC", id: "comerciantes-fc", pais: "PER", pagina: "america-sul.html" },
    { nome: "FC San Marcos", id: "fc-san-marcos-per", pais: "PER", pagina: "america-sul.html" },
    { nome: "Sport Loreto", id: "sport-loreto", pais: "PER", pagina: "america-sul.html" },
    { nome: "Defensor San Alejandro", id: "defensor-san-alejandro", pais: "PER", pagina: "america-sul.html" },
    { nome: "ADA Jaén", id: "ada-jaen", pais: "PER", pagina: "america-sul.html" },
    { nome: "Sportivo Huracán", id: "sportivo-huracan", pais: "PER", pagina: "america-sul.html" },
    { nome: "Defensor La Bocana", id: "defensor-la-bocana", pais: "PER", pagina: "america-sul.html" },
    { nome: "Deportivo Hualgayoc", id: "deportivo-hualgayoc", pais: "PER", pagina: "america-sul.html" },
    { nome: "Sport Rosario", id: "sport-rosario", pais: "PER", pagina: "america-sul.html" },
    { nome: "Total Chalaco", id: "total-chalaco", pais: "PER", pagina: "america-sul.html" },
    { nome: "Unión Tarapoto", id: "union-tarapoto", pais: "PER", pagina: "america-sul.html" },
    { nome: "Alfredo Salinas", id: "alfredo-salinas", pais: "PER", pagina: "america-sul.html" },
    { nome: "Unión Fuerza Minera", id: "union-fuerza-minera", pais: "PER", pagina: "america-sul.html" },
    { nome: "Deportivo Wanka", id: "deportivo-wanka", pais: "PER", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "PER", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "PER", pagina: "america-sul.html" },

    /* Clubes do Uruguai */
    { nome: "Nacional", id: "nacional", pais: "URU", pagina: "america-sul.html" },
    { nome: "Peñarol", id: "penarol", pais: "URU", pagina: "america-sul.html" },
    { nome: "Artigas Sport Clube", id: "artigas-sport-clube", pais: "URU", pagina: "america-sul.html" },
    { nome: "Bella Vista", id: "bella-vista", pais: "URU", pagina: "america-sul.html" },
    { nome: "Central Español", id: "central-espanol", pais: "URU", pagina: "america-sul.html" },
    { nome: "Cerro", id: "cerro", pais: "URU", pagina: "america-sul.html" },
    { nome: "Cerro Largo", id: "cerro-largo", pais: "URU", pagina: "america-sul.html" },
    { nome: "Danubio", id: "danubio", pais: "URU", pagina: "america-sul.html" },
    { nome: "Defensor Sporting", id: "defensor-sporting", pais: "URU", pagina: "america-sul.html" },
    { nome: "El Tanque Sisley", id: "el-tanque-sisley", pais: "URU", pagina: "america-sul.html" },
    { nome: "Fénix", id: "fenix-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Lavalleja AC", id: "lavalleja-ac", pais: "URU", pagina: "america-sul.html" },
    { nome: "Juventud", id: "juventud-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Liverpool", id: "liverpool-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Montevideo Wanderers", id: "montevideo-wanderers", pais: "URU", pagina: "america-sul.html" },
    { nome: "Progreso", id: "progreso-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Racing", id: "racing-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "River Plate", id: "river-plate-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Atenas", id: "atenas-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Boston River", id: "boston-river", pais: "URU", pagina: "america-sul.html" },
    { nome: "Cerrito", id: "cerrito", pais: "URU", pagina: "america-sul.html" },
    { nome: "Deportivo Maldonado", id: "deportivo-maldonado", pais: "URU", pagina: "america-sul.html" },
    { nome: "Huracán", id: "huracan-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Miramar Misiones", id: "miramar-misiones-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Plaza Colonia", id: "plaza-colonia-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Rampla Juniors", id: "rampla-juniors-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Rentistas", id: "rentistas-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Rocha", id: "rocha-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Sud América", id: "sud-america-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Tacuarembó", id: "tacuarembo-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Torque", id: "torque-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Villa Española", id: "villa-espanola-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Albion", id: "albion-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Alto Perú", id: "alto-peru-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Basáñez", id: "basanez-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Canadian", id: "canadian-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Colón", id: "colon-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "La Luz", id: "la-luz-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Mar de Fondo", id: "mar-de-fondo-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Oriental", id: "oriental-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Platense", id: "platense-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Potencia", id: "potencia-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Salus", id: "salus-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Uruguay Montevideo", id: "uruguay-montevideo-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Deportivo Colonia", id: "deportivo-colonia-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Durazno", id: "durazno-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Frontera Rivera", id: "frontera-rivera-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Huracán Buceo", id: "huracan-buceo-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Libertad de San Carlos", id: "libertad-de-san-carlos-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Parque del Plata", id: "parque-del-plata-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Paysandú FC", id: "paysandu-fc-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Paysandú Bella Vista", id: "paysandu-bella-vista-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Piriápolis FC", id: "piriapolis-fc-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Río Negro", id: "rio-negro-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Salto", id: "salto-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Terremoto", id: "terremoto-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Villa Teresa", id: "villa-teresa-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "Wanderers", id: "wanderers-artigas-uru", pais: "URU", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "URU", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "URU", pagina: "america-sul.html" },

    /* Clubes da Venezuela */
    { nome: "Carabobo", id: "carabobo-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Deportivo Tachira", id: "deportivo-tachira-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Caracas FC", id: "caracas-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Academia Puerto Cabello", id: "academia-puerto-cabello-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Deportivo La Guaira", id: "deportivo-la-guaira-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Estudiantes de Merida", id: "estudiantes-de-merida-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Monagas SC", id: "monagas-sc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Zamora FC", id: "zamora-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Mineros de Guayana", id: "mineros-de-guayana-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Universidad Central", id: "universidad-central-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Rayo Zuliano", id: "rayo-zuliano-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Portuguesa FC", id: "portuguesa-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Trujillanos FC", id: "trujillanos-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Metropolitanos FC", id: "metropolitanos-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Inter de Barinas", id: "inter-de-barinas-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Anzoategui FC", id: "anzoategui-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Yaracuyanos FC", id: "yaracuyanos-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Deportivo Petare", id: "deportivo-petare-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Llaneros", id: "llaneros-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Aragua FC", id: "aragua-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Angostura FC", id: "angostura-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Atletico El Vigia", id: "atletico-el-vigia-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Maritimo La Guaira", id: "maritimo-la-guaira-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Atletico Venezuela", id: "atletico-venezuela-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Ureña SC", id: "urena-sc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Real Frontera SC", id: "real-frontera-sc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Tucanes de Amazonas", id: "tucanes-de-amazonas-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Estudiantes de Caracas", id: "estudiantes-de-caracas-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "LALA FC", id: "lala-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Deportivo JBL", id: "deportivo-jbl-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Yaracuy FC", id: "yaracuy-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Deportivo Miranda", id: "deportivo-miranda-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Gran Valencia", id: "gran-valencia-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Union Atletico Maracaibo", id: "union-atletico-maracaibo-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Potros de Barinas", id: "potros-de-barinas-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Atletico Socopo", id: "atletico-socopo-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "UA Falcon", id: "ua-falcon-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Margarita FC", id: "margarita-fc-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Loteria del Tachira", id: "loteria-del-tachira-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Dynamo Puerto", id: "dynamo-puerto-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Union Local Andina", id: "union-local-andina-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "Arroceros de Calabozo", id: "arroceros-de-calabozo-ven", pais: "VEN", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "VEN", pagina: "america-sul.html" },


    /*CONCACAF - América do Norte, Central e Caribe*/

    /*Zona norte-americana (NAFU) - 3*/

    /* Clubes da Canadá */
    { nome: "Toronto FC", id: "toronto-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "CF Montréal", id: "cf-montreal", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Vancouver Whitecaps FC", id: "vancouver-whitecaps", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Forge FC", id: "forge-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Atlético Ottawa", id: "atletico-ottawa", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Cavalry FC", id: "cavalry-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "HFX Wanderers", id: "hfx-wanderers", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Pacific FC", id: "pacific-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "York United", id: "york-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Alliance United", id: "alliance-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Vaughan Azzurri", id: "vaughan-azzurri", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "North Toronto Nitros", id: "north-toronto-nitros", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "TSS FC Rovers", id: "tss-fc-rovers", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Altitude FC", id: "altitude-fc-can", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "AS Blainville", id: "as-blainville", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Laval", id: "fc-laval-can", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Guelph United", id: "guelph-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Hamilton United", id: "hamilton-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Scrosoppi FC", id: "scrosoppi-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Simcoe County Rovers", id: "simcoe-county-rovers", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Waterloo United", id: "waterloo-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Nautsa'mawt FC", id: "nautsamawt-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Unity FC", id: "unity-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "AS Laval", id: "as-laval", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Celtix du Haut-Richelieu", id: "celtix-haut-richelieu", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "CS Longueuil", id: "cs-longueuil", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Gatineau", id: "fc-gatineau", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Mont-Royal Outremont", id: "mont-royal-outremont", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "CAN", pagina: "america-norte-central-caribe.html" },

    /* Clubes dos Estados Unidos */
    { nome: "Atlanta United", id: "atlanta-united", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Seattle Sounders", id: "seattle-sounders", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Portland Timbers", id: "portland-timbers", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "San Jose Earthquakes", id: "san-jose-earthquakes", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "LA Galaxy", id: "la-galaxy", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Los Angeles FC", id: "los-angeles-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Nashville SC", id: "nashville-sc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "New York City FC", id: "new-york-city-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Inter Miami CF", id: "inter-miami", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Birmingham Legion FC", id: "birmingham-legion", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Phoenix Rising FC", id: "phoenix-rising", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Arizona", id: "fc-arizona", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Tucson", id: "fc-tucson", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Sporting Arizona", id: "sporting-arizona", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Charlotte FC", id: "charlotte-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Chicago Fire FC", id: "chicago-fire", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Cincinnati", id: "fc-cincinnati", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Columbus Crew", id: "columbus-crew", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "D.C. United", id: "dc-united", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "New England Revolution", id: "new-england-revolution", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "New York Red Bulls", id: "new-york-red-bulls", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Orlando City SC", id: "orlando-city", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Philadelphia Union", id: "philadelphia-union", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Austin FC", id: "austin-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Colorado Rapids", id: "colorado-rapids", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Dallas", id: "fc-dallas", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Houston Dynamo", id: "houston-dynamo", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Sporting Kansas City", id: "sporting-kansas-city", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Minnesota United FC", id: "minnesota-united", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Real Salt Lake", id: "real-salt-lake", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "San Diego FC", id: "san-diego-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "St. Louis City SC", id: "st-louis-city", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "USA", pagina: "america-norte-central-caribe.html" },

    /* Clubes do México */
    { nome: "Club América", id: "club-america-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Monterrey", id: "monterrey-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Cruz Azul", id: "cruz-azul-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Toluca", id: "toluca-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Tigres UANL", id: "tigres-uanl-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Club León", id: "club-leon-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Pumas", id: "pumas-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Pachuca", id: "pachuca-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Guadalajara", id: "guadalajara-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Club Tijuana", id: "club-tijuana-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Santos Laguna", id: "santos-laguna-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Atlas", id: "atlas-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Atlético San Luis", id: "atletico-san-luis-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Necaxa", id: "necaxa-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Juárez", id: "fc-juarez-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Mineros de Zacatecas", id: "mineros-de-zacatecas-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Club Puebla", id: "club-puebla-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Querétaro FC", id: "queretaro-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Mazatlán FC", id: "mazatlan-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Veracruz", id: "veracruz-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Lobos BUAP", id: "lobos-buap-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Atlante", id: "atlante-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Celaya FC", id: "celaya-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Leones Negros de la UdeG", id: "leones-negros-de-la-udeg-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Cancún FC", id: "cancun-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Correcaminos UAT", id: "correcaminos-uat-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Venados FC", id: "venados-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Dorados de Sinaloa", id: "dorados-de-sinaloa-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Jaiba Brava", id: "jaiba-brava-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Alebrijes de Oaxaca", id: "alebrijes-de-oaxaca-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Atlético Morelia", id: "atletico-morelia-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Irapuato", id: "irapuato-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Cimarrones de Sonora", id: "cimarrones-de-sonora-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Tlaxcala", id: "tlaxcala-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Atlético La Paz", id: "atletico-la-paz-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Tepatitlán FC", id: "tepatitlan-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "La Piedad", id: "la-piedad-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Alacranes de Durango", id: "alacranes-de-durango-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Pioneros de Cancún", id: "pioneros-de-cancun-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Gavilanes FC", id: "gavilanes-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Tritones Vallarta MFC", id: "tritones-vallarta-mfc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Inter Playa del Carmen", id: "inter-playa-del-carmen-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "CD Tapatío", id: "cd-tapatio-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Tecos FC", id: "tecos-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Colima FC", id: "colima-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Mineros de Fresnillo", id: "mineros-de-fresnillo-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Montañeses FC", id: "montaneses-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Toros Neza FC", id: "toros-neza-fc-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Tuzos de la UA de Zacatecas", id: "tuzos-de-la-ua-de-zacatecas-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "Universidad Autónoma de Zacatecas", id: "universidad-autonoma-de-zacatecas-mex", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "MEX", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "MEX", pagina: "america-norte-central-caribe.html" },

    /*Zona centro-americana (UNCAF) - 7*/

    /* clubes de Belize */
    { nome: "Verdes FC", id: "verdes-fc-blz", pais: "BLZ", pagina: "america-norte-central-caribe.html" },
    { nome: "Altitude FC", id: "altitude-fc-blz", pais: "BLZ", pagina: "america-norte-central-caribe.html" },
    { nome: "San Pedro Pirates", id: "san-pedro-pirates-blz", pais: "BLZ", pagina: "america-norte-central-caribe.html" },
    { nome: "Belmopan Bandits", id: "belmopan-bandits-blz", pais: "BLZ", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "BLZ", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "BLZ", pagina: "america-norte-central-caribe.html" },

    /*Clubes da Costa Rica*/
    { nome: "Alajuelense", id: "alajuelense-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Deportivo Saprissa", id: "deportivo-saprissa-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Herediano", id: "herediano-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Cartaginés", id: "cartagines-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Municipal Liberia", id: "municipal-liberia-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Pérez Zeledón", id: "perez-zeledon-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Sporting FC", id: "sporting-fc-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Puntarenas FC", id: "puntarenas-fc-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Santos de Guápiles", id: "santos-de-guapiles-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "San Carlos", id: "san-carlos-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Universidad de Costa Rica", id: "universidad-de-costa-rica-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "AD Carmelita", id: "ad-carmelita-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Municipal Grecia", id: "municipal-grecia-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Guadalupe FC", id: "guadalupe-fc-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "AD Guanacasteca", id: "ad-guanacasteca-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Uruguay de Coronado", id: "uruguay-de-coronado-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "ADR Jicaral", id: "adr-jicaral-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Barrio México", id: "barrio-mexico-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Santa Ana FC", id: "santa-ana-fc-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "Escorpiones de Belén FC", id: "escorpiones-de-belen-fc-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Moravia FCM", id: "fc-moravia-fcm-crc", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "CRC", pagina: "america-norte-central-caribe.html" },
    { nome: "", id: "", pais: "CRC", pagina: "america-norte-central-caribe.html" },

    /*Clubes de El Salvador*/
    { nome: "", id: " -slv", pais: "SLV", pagina: "america-norte-central-caribe.html" }, 
    { nome: "", id: " -slv", pais: "SLV", pagina: "america-norte-central-caribe.html" },




    /*CAF-África*/
    /* Clubes da Áfica do Sul */
    { nome: "Mamelodi Sundowns", id: "mamelodi-sundowns", pais: "RSA", pagina: "africa.html" },
    { nome: "Santos", id: "santos-rsa", pais: "RSA", pagina: "africa.html" },
    { nome: "", id: "", pais: "RSA", pagina: "africa.html" },
    { nome: "", id: "", pais: "RSA", pagina: "africa.html" },
    { nome: "", id: "", pais: "RSA", pagina: "africa.html" },
    { nome: "", id: "", pais: "RSA", pagina: "africa.html" },

    /* Clubes do Egito*/
    { nome: "Pyramids", id: "pyramids", pais: "EGY", pagina: "africa.html" },
    { nome: "", id: "", pais: "EGY", pagina: "africa.html" },
    { nome: "", id: "", pais: "EGY", pagina: "africa.html" },

    /*UEFA-Europa*/
    /* Clubes da Espanha */
    { nome: "Real Madrid", id: "real-madrid", pais: "ESP", pagina: "europa.html" },
    { nome: "FC Barcelona", id: "barcelona", pais: "ESP", pagina: "europa.html" },
    { nome: "Atlético de Madrid", id: "atletico-de-madrid", pais: "ESP", pagina: "europa.html" },
    { nome: "Sevilla FC", id: "sevilla", pais: "ESP", pagina: "europa.html" },


    /*AFC-Ásia*/


    /*OFC-Oceania*/










];