const CLUBES = [
    /* Clubes da Argentina */
    { nome: "Boca Juniors", id: "boca-juniors", pais: "ARG", pagina: "america-sul.html" },
    { nome: "River Plate", id: "river-plate", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Independiente", id: "independiente", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Racing Club", id: "racing-club", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Lorenzo", id: "san-lorenzo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Estudiantes de La Plata", id: "estudiantes-de-la-plata", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Newell's Old Boys", id: "newells-old-boys", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Rosario Central", id: "rosario-central", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Velez Sarsfield", id: "velez-sarsfield", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentinos Juniors", id: "argentinos-juniors", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Club Atlético Huracán", id: "club-atletico-huracan", pais: "ARG", pagina: "america-sul.html" },
    { nome: "gimnasia y Esgrima La Plata", id: "gimnasia-y-esgrima-la-plata", pais: "ARG", pagina: "america-sul.html" },
    { nome: "gimnasia y Esgrima de Mendoza", id: "gimnasia-y-esgrima-de-mendoza", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Lanús-ARG", id: "lanus", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Banfield-ARG", id: "banfield", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Talleres de Córdoba-ARG", id: "talleres-de-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Colón de Santa Fe-ARG", id: "colon-de-santa-fe", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Unión de Santa Fe-ARG", id: "union-de-santa-fe", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensa y Justicia-ARG", id: "defensa-y-justicia", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Godoy Cruz-ARG", id: "godoy-cruz", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Arsenal de Sarandi-ARG", id: "arsenal-de-sarandi", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Tucumán-ARG", id: "atletico-tucuman", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Tigre-ARG", id: "tigre", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Platense-ARG", id: "platense", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Barracas Central-ARG", id: "barracas-central", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Central Córdoba-ARG", id: "central-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Instituto de Córdoba-ARG", id: "instituto-de-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Sarmiento-ARG", id: "sarmiento", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Belgrano de Córdoba-ARG", id: "belgrano-de-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Patronato-ARG", id: "patronato", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Aldosivi-ARG", id: "aldosivi", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Independiente Rivadavia-ARG", id: "independiente-rivadavia", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Boca Unidos-ARG", id: "boca-unidos", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Quilmes-ARG", id: "quilmes", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Almagro-ARG", id: "almagro", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Martín de San Juan-ARG", id: "san-martin-de-san-juan", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Martín de Tucumán-ARG", id: "san-martin-de-tucuman", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Gimnasia de Jujuy-ARG", id: "gimnasia-de-jujuy", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Ferro Carril Oeste-ARG", id: "ferro-carril-oeste", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Olimpo-ARG", id: "olimpo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Tristán Suárez-ARG", id: "tristan-suarez", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Chacarita Juniors-ARG", id: "chacarita-juniors", pais: "ARG", pagina: "america-sul.html" },
    { nome: "All Boys-ARG", id: "all-boys", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético de Rafaela-ARG", id: "atletico-de-rafaela", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Los Andes-ARG", id: "los-andes", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Riestra-ARG", id: "deportivo-riestra", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Agropecuario-ARG", id: "agropecuario", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Brown de Adrogué-ARG", id: "brown-de-adrogué", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensores de Belgrano-ARG", id: "defensores-de-belgrano", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Morón-ARG", id: "deportivo-moron", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Almirante Brown-ARG", id: "almirante-brown", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Mitre-ARG", id: "atletico-mitre", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Nueva Chicago-ARG", id: "nueva-chicago", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Santamarina-ARG", id: "santamarina", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Club Atlético Temperley-ARG", id: "club-atletico-temperley", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Villa Dálmine-ARG", id: "villa-dalmine", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Acassuso-ARG", id: "acassuso", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentino de Quilmes-ARG", id: "argentino-de-quilmes", pais: "ARG", pagina: "america-sul.html" },
    { nome: "El Porvenir-ARG", id: "el-porvenir", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensores de Cambaceres-ARG", id: "defensores-de-cambaceres", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlanta-ARG", id: "atlanta-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Colegiales-ARG", id: "colegiales", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Comunicaciones-ARG", id: "comunicaciones", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Club Deportivo Español-ARG", id: "club-deportivo-espanol", pais: "ARG", pagina: "america-sul.html" },

    /* Clubes da Bolívia */
    { nome: "The Strongest-BOL", id: "the-strongest", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Bolívar-BOL", id: "bolivar", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Jorge Wilstermann-BOL", id: "jorge-wilstermann", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Blooming-BOL", id: "blooming", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Oriente Petrolero-BOL", id: "oriente-petrolero", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Aurora-BOL", id: "aurora", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Nacional Potosí-BOL", id: "nacional-potosi", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Real Santa Cruz-BOL", id: "real-santa-cruz", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Guabirá-BOL", id: "guabira", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Royal Pari-BOL", id: "royal-pari", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Universitario de Vinto-BOL", id: "universitario-de-vinto", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Independiente Petrolero-BOL", id: "independiente-petrolero", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Always Ready-BOL", id: "always-ready", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Real Potosí-BOL", id: "real-potosi", pais: "BOL", pagina: "america-sul.html" },
    { nome: "San José-BOL", id: "san-jose", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Universitario de Sucre-BOL", id: "universitario-de-sucre", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Palmaflor-BOL", id: "palmaflor", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Vaca Díez-BOL", id: "vaca-diez", pais: "BOL", pagina: "america-sul.html" },

    /* Clubes do Brasil */
    { nome: "Santos FC-BRA", id: "santos-fc", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Corinthians-BRA", id: "corinthians", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Chapecoense-BRA", id: "chapecoense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Botafogo-RJ-BRA", id: "botafogo-rj", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Náutico-RR-BRA", id: "nautico-rr", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Náutico-PE-BRA", id: "nautico-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Santa Cruz-PE-BRA", id: "santa-cruz-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Sport-PE-BRA", id: "sport", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Globo-RN-BRA", id: "globo-rn", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Fortaleza-BRA", id: "fortaleza", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Ceará-BRA", id: "ceara", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Floresta-BRA", id: "floresta", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Cuiabá-BRA", id: "cuiaba", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Bahia-BRA", id: "bahia", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Internacional-BRA", id: "internacional", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Grêmio-BRA", id: "gremio", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Brusque-BRA", id: "brusque", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Luverdense-BRA", id: "luverdense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Serra Talhada-BRA", id: "serra-talhada", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Manaus-BRA", id: "manaus", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Treze - PB-BRA", id: "treze-pb", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Botafogo- PB-BRA", id: "botafogo-pb", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Flamengo-BRA", id: "flamengo", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Palmeiras-BRA", id: "palmeiras", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Central-BRA", id: "central", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Porto-PE-BRA", id: "porto-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Criciúma-BRA", id: "criciuma", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Belo Jardim-BRA", id: "belo-jardim", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Chã Grande-BRA", id: "cha-grande", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Paulo-BRA", id: "sao-paulo", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Fluminense-BRA", id: "fluminense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Vasco da Gama-BRA", id: "vasco-da-gama", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Mirassol-BRA", id: "mirassol", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Cruzeiro-BRA", id: "cruzeiro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Athletico Paranaense-BRA", id: "athletico-paranaense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Mineiro-BRA", id: "atletico-mineiro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Petrolina-BRA", id: "petrolina", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Paysandu-BRA", id: "paysandu", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Avaí-BRA", id: "avai", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Athletic Club-BRA", id: "athletic-club", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Goianiense-BRA", id: "atletico-goianiense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Goiás-BRA", id: "goias", pais: "BRA", pagina: "america-sul.html" },
    { nome: "CRB-BRA", id: "crb", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Coritiba-BRA", id: "coritiba", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Paraná Clube-BRA", id: "parana-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Londrina-BRA", id: "londrina", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Afogados da Ingazeira-BRA", id: "afogados-da-ingazeira", pais: "BRA", pagina: "america-sul.html" },
    { nome: "ASA de Arapiraca-BRA", id: "asa-de-arapiraca", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Ramalat Sport Club-BRA", id: "ramalat-sport-club", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Rio Branco Football Club-BRA", id: "rio-branco-football-club", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Acreano-BRA", id: "atletico-acreano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Galvez Esporte Clube-BRA", id: "galvez-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Humaitá Futebol Clube-BRA", id: "humaita-futebol-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Francisco Futebol Clube-BRA", id: "sao-francisco-futebol-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "ADESG-BRA", id: "adesg", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Náuas Esporte Clube-BRA", id: "nauas-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Raimundo-RR-BRA", id: "sao-raimundo-rr", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Tombense-BRA", id: "tombense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "XV de Piracicaba-BRA", id: "xv-de-piracicaba", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Ponte Preta-BRA", id: "ponte-preta", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Guarani-BRA", id: "guarani", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Salgueiro-BRA", id: "salgueiro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Nacional-AM-BRA", id: "nacional-am", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Fast Clube-BRA", id: "fast-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Raimundo-AM-BRA", id: "sao-raimundo-am", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Princesa do Solimões Esporte Clube-BRA", id: "princesa-do-solimoes-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Penarol-AM-BRA", id: "penarol-am", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Operário Esporte Clube-BRA", id: "operario-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Iranduba Futebol Clube-BRA", id: "iranduba-futebol-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Rio Negro-BRA", id: "rio-negro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Amazonas-BRA", id: "amazonas", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Boa Esporte-BRA", id: "boa-esporte", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Íbis-BRA", id: "ibis", pais: "BRA", pagina: "america-sul.html" },
    { nome: "E.C.Vitória-BRA", id: "e-c-vitoria", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Juventude-BRA", id: "juventude", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Caxias do Sul-BRA", id: "caxias-do-sul", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Figueirense-BRA", id: "figueirense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "América Pernambucano-BRA", id: "america-pernambucano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "América de Natal-BRA", id: "america-de-natal", pais: "BRA", pagina: "america-sul.html" },
    { nome: "ABC-BRA", id: "abc", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Confiança-BRA", id: "confianca", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Lagarto-BRA", id: "lagarto", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Paragominas-BRA", id: "paragominas", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Cianorte-BRA", id: "cianorte", pais: "BRA", pagina: "america-sul.html" },

    /* Clubes do Chile */
    { nome: "Colo-Colo-CHI", id: "colo-colo", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Universidad de Chile-CHI", id: "universidad-de-chile", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Universidad Católica-CHI", id: "universidad-catolica", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Deportivo Union Espaola-CHI", id: "union-espanola", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Audax Italiano-CHI", id: "audax-italiano", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Everton de Viña del Mar-CHI", id: "everton-de-vina-del-mar", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Santiago Wanderers-CHI", id: "santiago-wanderers", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Nublense-CHI", id: "nublense", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Huachipato-CHI", id: "huachipato", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Palestino-CHI", id: "palestino", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Cobresal-CHI", id: "cobresal", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Temuco-CHI", id: "deportes-temuco", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Rangers de Talca-CHI", id: "rangers-chi", pais: "CHI", pagina: "america-sul.html" },

    /* Clubes da Colômbia*/
    { nome: "Atlético Nacional-COL", id: "atletico-nacional", pais: "COL", pagina: "america-sul.html" },
    { nome: "Millonarios FC-COL", id: "millonarios", pais: "COL", pagina: "america-sul.html" },

    /* Clubes do Uruguai */
    { nome: "Nacional-URU", id: "nacional", pais: "URU", pagina: "america-sul.html" },
    { nome: "Peñarol-URU", id: "penarol", pais: "URU", pagina: "america-sul.html" },

    /* Clubes dos Estados Unidos */
    { nome: "Atlanta United-USA", id: "atlanta-united", pais: "USA", pagina: "america-norte-central-caribe.html" },

    /* Clubes da Espanha */
    { nome: "Real Madrid-ESP", id: "real-madrid", pais: "ESP", pagina: "europa.html" },
    { nome: "FC Barcelona-ESP", id: "barcelona", pais: "ESP", pagina: "europa.html" },
    { nome: "Atlético de Madrid-ESP", id: "atletico-de-madrid", pais: "ESP", pagina: "europa.html" },
    { nome: "Sevilla FC-ESP", id: "sevilla", pais: "ESP", pagina: "europa.html" },










];