const CLUBES = [
    /*CONMEBOL - América do Sul*/

    /* Clubes da Argentina */
    { nome: "Boca Juniors", id: "boca-juniors", pais: "ARG", pagina: "america-sul.html" },
    { nome: "River Plate", id: "river-plate", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Independiente", id: "independiente", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Racing Club", id: "racing-club", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Lorenzo", id: "san-lorenzo-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Estudiantes de La Plata", id: "estudiantes-de-la-plata", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Newell's Old Boys", id: "newells-old-boys", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Rosario Central", id: "rosario-central", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Velez Sarsfield", id: "velez-sarsfield", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentinos Juniors", id: "argentinos-juniors", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Club Atlético Huracán", id: "huracan", pais: "ARG", pagina: "america-sul.html" },
    { nome: "gimnasia y Esgrima La Plata", id: "gimnasia-y-esgrima-la-plata", pais: "ARG", pagina: "america-sul.html" },
    { nome: "gimnasia y Esgrima de Mendoza", id: "gimnasia-y-esgrima-de-mendoza", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Lanús", id: "lanus", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Banfield", id: "banfield", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Talleres de Córdoba", id: "talleres-de-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Colón de Santa Fe", id: "colon-de-santa-fe", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Unión de Santa Fe", id: "union-de-santa-fe", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensa y Justicia", id: "defensa-y-justicia", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Godoy Cruz", id: "godoy-cruz", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Arsenal de Sarandi", id: "arsenal-de-sarandi", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Tucumán", id: "atletico-tucuman", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Tigre", id: "tigre", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Platense", id: "platense", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Barracas Central", id: "barracas-central", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Central Córdoba", id: "central-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Instituto de Córdoba", id: "instituto-de-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Sarmiento", id: "sarmiento", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Belgrano de Córdoba", id: "belgrano-de-cordoba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Patronato", id: "patronato", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Aldosivi", id: "aldosivi", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Independiente Rivadavia", id: "independiente-rivadavia", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Boca Unidos", id: "boca-unidos", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Quilmes", id: "quilmes", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Almagro", id: "almagro", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Martín de San Juan", id: "san-martin-de-san-juan", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Martín de Tucumán", id: "san-martin-de-tucuman", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Gimnasia de Jujuy", id: "gimnasia-de-jujuy", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Ferro Carril Oeste", id: "ferro-carril-oeste", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Olimpo", id: "olimpo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Tristán Suárez", id: "tristan-suarez", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Chacarita Juniors", id: "chacarita-juniors", pais: "ARG", pagina: "america-sul.html" },
    { nome: "All Boys", id: "all-boys", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético de Rafaela", id: "atletico-de-rafaela", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Los Andes", id: "los-andes", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Riestra", id: "deportivo-riestra", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Agropecuario", id: "agropecuario", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Brown de Adrogué", id: "brown-de-adrogué", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensores de Belgrano", id: "defensores-de-belgrano", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Morón", id: "deportivo-moron", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Almirante Brown", id: "almirante-brown", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Mitre", id: "atletico-mitre", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Nueva Chicago", id: "nueva-chicago", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Santamarina", id: "santamarina", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Club Atlético Temperley", id: "club-atletico-temperley", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Villa Dálmine", id: "villa-dalmine", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Acassuso", id: "acassuso", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentino de Quilmes", id: "argentino-de-quilmes", pais: "ARG", pagina: "america-sul.html" },
    { nome: "El Porvenir", id: "el-porvenir", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensores de Cambaceres", id: "defensores-de-cambaceres", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlanta", id: "atlanta-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Colegiales", id: "atletico-colegiales-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Comunicaciones", id: "comunicaciones", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Club Deportivo Español", id: "club-deportivo-espanol", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Defensores Unidos", id: "defensores-unidos", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Estudiantes de Buenos Aires", id: "estudiantes-ba", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Fénix", id: "fenix", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Flandria", id: "flandria", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Sacachispas", id: "sacachispas", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Miguel", id: "san-miguel", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Telmo", id: "san-telmo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Talleres (RE)", id: "talleres-re", pais: "ARG", pagina: "america-sul.html" },
    { nome: "UAI Urquiza", id: "uai-urquiza", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentino (Merlo)", id: "argentino-de-merlo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Armenio", id: "deportivo-armenio", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Berazategui", id: "berazategui", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Cañuelas", id: "canuelas", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Laferrere", id: "deportivo-laferrere", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Dock Sud", id: "dock-sud", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Sportivo Barracas", id: "sportivo-barracas", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Sportivo Italiano", id: "sportivo-italiano", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Ferrocarril Midland", id: "ferrocarril-midland", pais: "ARG", pagina: "america-sul.html" },
    { nome: "J.J. Urquiza", id: "jj-urquiza", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Merlo", id: "deportivo-merlo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Luján", id: "lujan", pais: "ARG", pagina: "america-sul.html" },
    { nome: "San Martín (Burzaco)", id: "san-martin-burzaco", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Argentino (Rosário)", id: "argentino-de-rosario", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlas-ARG", id: "atlas-arg", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Central Ballester", id: "central-ballester", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Centro Español", id: "centro-espanol", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Claypole", id: "claypole", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Paraguayo", id: "deportivo-paraguayo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Juventud Unida", id: "juventud-unida", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Liniers", id: "liniers", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Atlético Lugano", id: "atletico-lugano", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Deportivo Muñiz", id: "deportivo-muniz", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Puerto Nuevo", id: "puerto-nuevo", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Real Pilar", id: "real-pilar", pais: "ARG", pagina: "america-sul.html" },
    { nome: "Yupanqui", id: "yupanqui", pais: "ARG", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "ARG", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "ARG", pagina: "america-sul.html" },


    /* Clubes da Bolívia */
    { nome: "The Strongest", id: "the-strongest", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Bolívar", id: "bolivar", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Jorge Wilstermann", id: "jorge-wilstermann", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Blooming", id: "blooming", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Oriente Petrolero", id: "oriente-petrolero", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Aurora", id: "aurora", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Nacional Potosí", id: "nacional-potosi", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Real Santa Cruz", id: "real-santa-cruz", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Guabirá", id: "guabira", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Royal Pari", id: "royal-pari", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Universitario de Vinto", id: "universitario-de-vinto", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Independiente Petrolero", id: "independiente-petrolero", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Always Ready", id: "always-ready", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Real Potosí", id: "real-potosi", pais: "BOL", pagina: "america-sul.html" },
    { nome: "San José", id: "san-jose", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Universitario de Sucre", id: "universitario-de-sucre", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Palmaflor", id: "palmaflor", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Vaca Díez", id: "vaca-diez", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Chaco Petrolero", id: "chaco-petrolero", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Destroyer's", id: "destroyers", pais: "BOL", pagina: "america-sul.html" },
    { nome: "Unión Central", id: "union-central", pais: "BOL", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BOL", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BOL", pagina: "america-sul.html" },


    /* Clubes do Brasil */
    { nome: "Santos FC", id: "santos-fc", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Corinthians", id: "corinthians", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Chapecoense", id: "chapecoense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Botafogo-RJ", id: "botafogo-rj", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Náutico-RR", id: "nautico-rr", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Náutico-PE", id: "nautico-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Santa Cruz-PE", id: "santa-cruz-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Sport-PE", id: "sport", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Globo-RN", id: "globo-rn", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Fortaleza", id: "fortaleza", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Ceará", id: "ceara", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Floresta", id: "floresta", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Cuiabá", id: "cuiaba", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Bahia", id: "bahia", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Internacional", id: "internacional", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Grêmio", id: "gremio", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Brusque", id: "brusque", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Luverdense", id: "luverdense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Serra Talhada", id: "serra-talhada", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Manaus", id: "manaus", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Treze - PB", id: "treze-pb", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Botafogo- PB", id: "botafogo-pb", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Flamengo", id: "flamengo", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Palmeiras", id: "palmeiras", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Central", id: "central", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Porto-PE", id: "porto-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Criciúma", id: "criciuma", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Belo Jardim", id: "belo-jardim", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Chã Grande", id: "cha-grande", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Paulo", id: "sao-paulo", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Fluminense", id: "fluminense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Vasco da Gama", id: "vasco-da-gama", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Mirassol", id: "mirassol", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Cruzeiro", id: "cruzeiro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Athletico Paranaense", id: "athletico-paranaense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Mineiro", id: "atletico-mineiro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Petrolina", id: "petrolina", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Paysandu", id: "paysandu", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Avaí", id: "avai", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Athletic Club", id: "athletic-club", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Goianiense", id: "atletico-goianiense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Goiás", id: "goias", pais: "BRA", pagina: "america-sul.html" },
    { nome: "CRB", id: "crb", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Coritiba", id: "coritiba", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Paraná Clube", id: "parana-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Londrina", id: "londrina", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Afogados da Ingazeira", id: "afogados-da-ingazeira", pais: "BRA", pagina: "america-sul.html" },
    { nome: "ASA de Arapiraca", id: "asa-de-arapiraca", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Ramalat Sport Club", id: "ramalat-sport-club", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Rio Branco-AC", id: "rio-branco-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Acreano", id: "atletico-acreano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Galvez Esporte Clube", id: "galvez-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Humaitá Futebol Clube", id: "humaita-futebol-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Francisco Futebol Clube", id: "sao-francisco-futebol-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "ADESG", id: "adesg", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Náuas Esporte Clube", id: "nauas-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Raimundo-RR", id: "sao-raimundo-rr", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Tombense", id: "tombense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "XV de Piracicaba", id: "xv-de-piracicaba", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Ponte Preta", id: "ponte-preta", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Guarani", id: "guarani-bra", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Salgueiro", id: "salgueiro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Fast Clube", id: "fast-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "São Raimundo-AM", id: "sao-raimundo-am", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Princesa do Solimões Esporte Clube", id: "princesa-do-solimoes-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Penarol-AM", id: "penarol-am", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Operário Esporte Clube", id: "operario-esporte-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Iranduba Futebol Clube", id: "iranduba-futebol-clube", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Rio Negro", id: "rio-negro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Amazonas", id: "amazonas", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Boa Esporte", id: "boa-esporte", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Íbis", id: "ibis", pais: "BRA", pagina: "america-sul.html" },
    { nome: "E.C.Vitória", id: "e-c-vitoria", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Juventude", id: "juventude", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Caxias do Sul", id: "caxias-do-sul", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Figueirense", id: "figueirense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "América Pernambucano", id: "america-pernambucano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "América de Natal", id: "america-de-natal", pais: "BRA", pagina: "america-sul.html" },
    { nome: "ABC", id: "abc", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Confiança", id: "confianca", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Lagarto", id: "lagarto", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Paragominas", id: "paragominas", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Cianorte", id: "cianorte", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Icasa", id: "icasa", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Clube Juventus-AC", id: "atletico-clube-juventus-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Clube Atlético Juventus-SP", id: "clube-atletico-juventus-sp", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Nacional-AM", id: "nacional-am", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Nacional-SP", id: "nacional-sp", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Independência-AC", id: "independencia-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Acriano", id: "acriano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Alto Acre", id: "alto-acre", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Andirá Esporte Clube", id: "andira-ec", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Grêmio Acreano", id: "gremio-acreano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Plácido de Castro", id: "placido-de-castro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Vasco da Gama-AC", id: "vasco-da-gama-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Santa Cruz-AC", id: "santa-cruz-ac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Amax", id: "amax", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Jaguar-PE", id: "jaguar-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Retrô", id: "retro", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Atlético Pernambucano", id: "atletico-pernambucano", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Vera Cruz-PE", id: "vera-cruz-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Vitória-PE", id: "vitoria-pe", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Campinense", id: "campinense", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Altos-PI", id: "altos-pi", pais: "BRA", pagina: "america-sul.html" },
    { nome: "River-PI", id: "river-pi", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Flamengo-PI", id: "flamengo-pi", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Parnahyba-PI", id: "parnahyba-pi", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Moto Club-MA", id: "moto-club-ma", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Sampaio Corrêa-MA", id: "sampaio-correa-ma", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Maranhão (MAC)", id: "maranhao-mac", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Imperatriz", id: "imperatriz", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Tocantins", id: "tocantins", pais: "BRA", pagina: "america-sul.html" },
    { nome: "Patriotas-PR", id: "patriotas-pr", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "BRA", pagina: "america-sul.html" },

    /* Clubes do Chile */
    { nome: "Colo-Colo", id: "colo-colo", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Universidad de Chile", id: "universidad-de-chile", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Universidad Católica del Chile", id: "universidad-catolica-del-chile", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Club Deportivo Union Espaola", id: "union-espanola", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Audax Italiano", id: "audax-italiano", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Everton de Viña del Mar", id: "everton-de-vina-del-mar", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Santiago Wanderers", id: "santiago-wanderers", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Nublense", id: "nublense", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Huachipato", id: "huachipato", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Palestino", id: "palestino", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Cobresal", id: "cobresal", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Deportes Temuco", id: "deportes-temuco", pais: "CHI", pagina: "america-sul.html" },
    { nome: "Rangers de Talca", id: "rangers-chi", pais: "CHI", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "CHI", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "CHI", pagina: "america-sul.html" },

    /* Clubes da Colômbia*/
    { nome: "Atlético Nacional", id: "atletico-nacional", pais: "COL", pagina: "america-sul.html" },
    { nome: "Millonarios FC", id: "millonarios", pais: "COL", pagina: "america-sul.html" },
    { nome: "Águilas Doradas", id: "aguilas-doradas", pais: "COL", pagina: "america-sul.html" },
    { nome: "Alianza", id: "alianza", pais: "COL", pagina: "america-sul.html" },
    { nome: "Atlético Bucaramanga", id: "atletico-bucaramanga", pais: "COL", pagina: "america-sul.html" },
    { nome: "América de Cali", id: "america-de-cali", pais: "COL", pagina: "america-sul.html" },
    { nome: "Boyacá Chicó", id: "boyaca-chico", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportes Tolima", id: "deportes-tolima", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportivo Cali", id: "deportivo-cali", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportivo Pasto", id: "deportivo-pasto", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportivo Pereira", id: "deportivo-pereira", pais: "COL", pagina: "america-sul.html" },
    { nome: "Envigado", id: "envigado", pais: "COL", pagina: "america-sul.html" },
    { nome: "Fortaleza CEIF", id: "fortaleza-ceif", pais: "COL", pagina: "america-sul.html" },
    { nome: "Independiente Medellín", id: "independiente-medellin", pais: "COL", pagina: "america-sul.html" },
    { nome: "Jaguares de Córdoba", id: "jaguares de cordoba", pais: "COL", pagina: "america-sul.html" },
    { nome: "Junior de Barranquilla", id: "junior-barranquilla", pais: "COL", pagina: "america-sul.html" },
    { nome: "La Equidad", id: "la-equidad", pais: "COL", pagina: "america-sul.html" },
    { nome: "Once Caldas", id: "once-caldas", pais: "COL", pagina: "america-sul.html" },
    { nome: "Patriotas", id: "patriotas-col", pais: "COL", pagina: "america-sul.html" },
    { nome: "Santa Fe", id: "santa-fe", pais: "COL", pagina: "america-sul.html" },
    { nome: "Atlético FC", id: "atletico-fc", pais: "COL", pagina: "america-sul.html" },
    { nome: "Atlético Huila", id: "atletico-huila", pais: "COL", pagina: "america-sul.html" },
    { nome: "Barranquilla FC", id: "barranquilla-fc", pais: "COL", pagina: "america-sul.html" },
    { nome: "Boca Juniors de Cali", id: "boca-juniors-cali", pais: "COL", pagina: "america-sul.html" },
    { nome: "Bogotá FC", id: "bogota-fc", pais: "COL", pagina: "america-sul.html" },
    { nome: "Cúcuta Deportivo", id: "cucuta-deportivo", pais: "COL", pagina: "america-sul.html" },
    { nome: "Deportes Quindío", id: "deportes-quindio", pais: "COL", pagina: "america-sul.html" },
    { nome: "Internacional Palmira", id: "internacional-palmira", pais: "COL", pagina: "america-sul.html" },
    { nome: "Itagüí Leones", id: "itagui-leones", pais: "COL", pagina: "america-sul.html" },
    { nome: "Llaneros", id: "llaneros", pais: "COL", pagina: "america-sul.html" },
    { nome: "Orsomarso", id: "orsomarso", pais: "COL", pagina: "america-sul.html" },
    { nome: "Real Cartagena", id: "real-cartagena", pais: "COL", pagina: "america-sul.html" },
    { nome: "Real Cundinamarca", id: "real-cundinamarca", pais: "COL", pagina: "america-sul.html" },
    { nome: "Real Santander", id: "real-santander", pais: "COL", pagina: "america-sul.html" },
    { nome: "Tigres", id: "tigres-col", pais: "COL", pagina: "america-sul.html" },
    { nome: "Unión Magdalena", id: "union-magdalena", pais: "COL", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "COL", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "COL", pagina: "america-sul.html" },

    /* Clubes do Equador */
    { nome: "LDU Quito", id: "ldu-quito", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Barcelona de Guayaquil", id: "barcelona-de-guayaquil", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Independiente del Valle", id: "independiente-del-valle", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Independiente Juniors", id: "independiente-juniors", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Emelec", id: "emelec", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Aucas", id: "aucas", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Guayaquil City", id: "guayaquil-city", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Manta FC", id: "manta-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Olmedo", id: "olmedo", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Deportivo Quito", id: "deportivo-quito", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Universidad Católica del Ecuador", id: "universidad-catolica-ecuador", pais: "ECU", pagina: "america-sul.html" },
    { nome: "LDU Portoviejo", id: "ldu-portoviejo", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Macará", id: "macara", pais: "ECU", pagina: "america-sul.html" },
    { nome: "El Nacional", id: "el-nacional", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Mushuc Runa", id: "mushuc-runa", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Técnico Universitario", id: "tecnico-universitario", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Orense SC", id: "orense-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Imbabura SC", id: "imbabura-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Deportivo Cuenca", id: "deportivo-cuenca", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Delfín SC", id: "delfin-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Deportivo Quevedo", id: "deportivo-quevedo", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Deportivo Azogues", id: "deportivo-azogues", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Gualaceo SC", id: "gualaceo-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Cumbaya FC", id: "cumbaya-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Vinotinto FC", id: "vinotinto-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Atlético Vinotinto", id: "atletico-vinotinto", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Libertad FC", id: "libertad-fc-ecu", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Chacaritas FC", id: "chacaritas-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Nueve de Octubre", id: "nueve-de-octubre", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Leones FC", id: "leones-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Buhos ULVR", id: "buhos-ulvr", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Clan Juvenil", id: "clan-juvenil", pais: "ECU", pagina: "america-sul.html" },
    { nome: "C.D. Espoli", id: "cd-espoli", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Fuerza Amarilla SC", id: "fuerza-amarilla-sc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "CSCD Grecia", id: "cscd-grecia", pais: "ECU", pagina: "america-sul.html" },
    { nome: "UT Cotopaxi", id: "ut-cotopaxi", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Atlético Porteño", id: "atletico-porteno", pais: "ECU", pagina: "america-sul.html" },
    { nome: "C.S. Patria", id: "cs-patria-ecu", pais: "ECU", pagina: "america-sul.html" },
    { nome: "C.D. Santa Rita", id: "cd-santa-rita", pais: "ECU", pagina: "america-sul.html" },
    { nome: "América de Quito", id: "america-de-quito", pais: "ECU", pagina: "america-sul.html" },
    { nome: "San Antonio", id: "san-antonio", pais: "ECU", pagina: "america-sul.html" },
    { nome: "CD Municipal Cañar", id: "cd-municipal-canar", pais: "ECU", pagina: "america-sul.html" },
    { nome: "Colón de Portoviejo", id: "colon-de-portoviejo", pais: "ECU", pagina: "america-sul.html" },
    { nome: "CD Ferroviarios", id: "cd-ferroviarios", pais: "ECU", pagina: "america-sul.html" },
    { nome: "CSD Vargas Torres", id: "csd-vargas-torres", pais: "ECU", pagina: "america-sul.html" },
    { nome: "22 de Julio FC", id: "vinte-e-dois-de-julio-fc", pais: "ECU", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "ECU", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "ECU", pagina: "america-sul.html" },

    /* Clubes do Paraguai */
    { nome: "Cerro Porteño", id: "cerro-porteno", pais: "PAR", pagina: "america-sul.html" },    
    { nome: "Nacional", id: "nacional-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Guaraní", id: "guarani-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Rubio Ñu", id: "rubio-nu", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Atlético Colegiales", id: "atletico-colegiales-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Tacuary", id: "tacuary", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sportivo Luqueño", id: "sportivo-luqueno", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sol de América", id: "sol-de-america", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Díaz", id: "general-diaz", pais: "PAR", pagina: "america-sul.html" },
    { nome: "River Plate", id: "river-plate-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "29 de Septiembre", id: "clube-29-de-septiembre", pais: "PAR", pagina: "america-sul.html" },
    { nome: "3 de Febrero", id: "3-de-febrero", pais: "PAR", pagina: "america-sul.html" },
    { nome: "1º de Marzo", id: "1-de-marzo", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Martín Ledesma", id: "general-martin-ledesma", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Cristóbal Colón", id: "cristobal-colon", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Capitán Figari", id: "capitan-figari", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Atlético Tembetary", id: "atletico-tembetary", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Atlântida", id: "atlantida", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Atlético Juventud", id: "atletico-juventud", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Caballero San Felipe", id: "general-caballero-san-felipe", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Oriental", id: "oriental", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Valois Rivarola", id: "valois-rivarola", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sport Colonial", id: "sport-colonial", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Benjamín Aceval", id: "benjamin-aceval", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Libertad", id: "libertad", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Presidente Hayes", id: "presidente-hayes", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Olímpia", id: "olimpia", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sportivo Trinidense", id: "sportivo-trinidense", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Silvio Pettirossi", id: "silvio-pettirossi", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Fernando de la Mora", id: "fernando-de-la-mora", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Independiente de Campo Grande", id: "independiente-campo-grande", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sport Colombia", id: "sport-colombia", pais: "PAR", pagina: "america-sul.html" },
    { nome: "San Lorenzo", id: "san-lorenzo-par", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Resistencia", id: "resistencia", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sportivo Iteño", id: "sportivo-iteno", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Caballero", id: "general-caballero", pais: "PAR", pagina: "america-sul.html" },
    { nome: "3 de Noviembre", id: "3-de-noviembre", pais: "PAR", pagina: "america-sul.html" },
    { nome: "12 de Octubre", id: "12-de-octubre", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Olímpia de Itá", id: "olimpia-de-ita", pais: "PAR", pagina: "america-sul.html" },
    { nome: "General Caballero de Campo Grande", id: "general-caballero-campo-grande", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Pilcomayo", id: "pilcomayo", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Nikkei Belmare", id: "nikkei-belmare", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Deportivo Pinozá", id: "deportivo-pinoza", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Deportivo Recoleta", id: "deportivo-recoleta", pais: "PAR", pagina: "america-sul.html" },
    { nome: "Sportivo Ameliano", id: "sportivo-ameliano", pais: "PAR", pagina: "america-sul.html" },




    /* Clubes do Uruguai */
    { nome: "Nacional", id: "nacional", pais: "URU", pagina: "america-sul.html" },
    { nome: "Peñarol", id: "penarol", pais: "URU", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "URU", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "URU", pagina: "america-sul.html" },
    { nome: "", id: "", pais: "URU", pagina: "america-sul.html" },


    /*CONCACAF - América do Norte, Central e Caribe*/

    /* Clubes da Canadá */
    { nome: "Toronto FC", id: "toronto-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "CF Montréal", id: "cf-montreal", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Vancouver Whitecaps FC", id: "vancouver-whitecaps", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Forge FC", id: "forge-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Atlético Ottawa", id: "atletico-ottawa", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Cavalry FC", id: "cavalry-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "HFX Wanderers", id: "hfx-wanderers", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Pacific FC", id: "pacific-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "York United", id: "york-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Alliance United", id: "alliance-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Vaughan Azzurri", id: "vaughan-azzurri", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "North Toronto Nitros", id: "north-toronto-nitros", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "TSS FC Rovers", id: "tss-fc-rovers", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Altitude FC", id: "altitude-fc-can", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "AS Blainville", id: "as-blainville", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Laval", id: "fc-laval-can", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Guelph United", id: "guelph-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Hamilton United", id: "hamilton-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Scrosoppi FC", id: "scrosoppi-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Simcoe County Rovers", id: "simcoe-county-rovers", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Waterloo United", id: "waterloo-united", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Nautsa'mawt FC", id: "nautsamawt-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Unity FC", id: "unity-fc", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "AS Laval", id: "as-laval", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Celtix du Haut-Richelieu", id: "celtix-haut-richelieu", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "CS Longueuil", id: "cs-longueuil", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Gatineau", id: "fc-gatineau", pais: "CAN", pagina: "america-norte-central-caribe.html" },
    { nome: "Mont-Royal Outremont", id: "mont-royal-outremont", pais: "CAN", pagina: "america-norte-central-caribe.html" },


    /* Clubes dos Estados Unidos */
    { nome: "Atlanta United", id: "atlanta-united", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Seattle Sounders", id: "seattle-sounders", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Portland Timbers", id: "portland-timbers", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "San Jose Earthquakes", id: "san-jose-earthquakes", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "LA Galaxy", id: "la-galaxy", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Los Angeles FC", id: "los-angeles-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Nashville SC", id: "nashville-sc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "New York City FC", id: "new-york-city-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Inter Miami CF", id: "inter-miami", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Birmingham Legion FC", id: "birmingham-legion", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Phoenix Rising FC", id: "phoenix-rising", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Arizona", id: "fc-arizona", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Tucson", id: "fc-tucson", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Sporting Arizona", id: "sporting-arizona", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Charlotte FC", id: "charlotte-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Chicago Fire FC", id: "chicago-fire", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Cincinnati", id: "fc-cincinnati", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Columbus Crew", id: "columbus-crew", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "D.C. United", id: "dc-united", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "New England Revolution", id: "new-england-revolution", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "New York Red Bulls", id: "new-york-red-bulls", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Orlando City SC", id: "orlando-city", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Philadelphia Union", id: "philadelphia-union", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Austin FC", id: "austin-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Colorado Rapids", id: "colorado-rapids", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "FC Dallas", id: "fc-dallas", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Houston Dynamo", id: "houston-dynamo", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Sporting Kansas City", id: "sporting-kansas-city", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Minnesota United FC", id: "minnesota-united", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "Real Salt Lake", id: "real-salt-lake", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "San Diego FC", id: "san-diego-fc", pais: "USA", pagina: "america-norte-central-caribe.html" },
    { nome: "St. Louis City SC", id: "st-louis-city", pais: "USA", pagina: "america-norte-central-caribe.html" },


    /*CAF-África*/
    /* Clubes da Áfica do Sul */
    { nome: "Mamelodi Sundowns", id: "mamelodi-sundowns", pais: "RSA", pagina: "africa.html" },
    { nome: "Santos", id: "santos-rsa", pais: "RSA", pagina: "africa.html" },
    { nome: "", id: "", pais: "RSA", pagina: "africa.html" },
    { nome: "", id: "", pais: "RSA", pagina: "africa.html" },
    { nome: "", id: "", pais: "RSA", pagina: "africa.html" },
    { nome: "", id: "", pais: "RSA", pagina: "africa.html" },

    /* Clubes do Egito*/
    { nome: "Pyramids", id: "pyramids", pais: "EGY", pagina: "africa.html" },
    { nome: "", id: "", pais: "EGY", pagina: "africa.html" },
    { nome: "", id: "", pais: "EGY", pagina: "africa.html" },

    /*UEFA-Europa*/
    /* Clubes da Espanha */
    { nome: "Real Madrid", id: "real-madrid", pais: "ESP", pagina: "europa.html" },
    { nome: "FC Barcelona", id: "barcelona", pais: "ESP", pagina: "europa.html" },
    { nome: "Atlético de Madrid", id: "atletico-de-madrid", pais: "ESP", pagina: "europa.html" },
    { nome: "Sevilla FC", id: "sevilla", pais: "ESP", pagina: "europa.html" },


    /*AFC-Ásia*/


    /*OFC-Oceania*/










];